Bootstrap: localimage
From: ubuntu2204.sif

%files
    requirements.txt

%post
    apt-get update -y
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        ca-certificates \
        curl \
        python3 \
        python3-pip

    curl -fsSL https://ollama.com/install.sh | sh

    rm -rf /var/lib/apt/lists/*

    pip install -r requirements.txt

%environment
    export OLLAMA_MODELS=/ollama
    export PATH=/usr/local/bin:$PATH
